Repository OpenSourceEconomics/respy, pull requests merged in 2020-08, with the labels that each got.

#371 Rename criterion functions & enhancements for MSM interface.
  .conda/meta.yaml
  development/documentation/scalability/run_single_scalability_exercise.py
  docs/conf.py
  docs/how_to_guides/msm.ipynb
  docs/how_to_guides/msm_estimation_exercise.ipynb
  docs/index.rst
  docs/release_notes.rst
  docs/tutorials/robinson_crusoe.ipynb
  respy/__init__.py
  respy/conftest.py
  respy/likelihood.py
  respy/method_of_simulated_moments.py
  respy/simulate.py
  respy/solve.py
  respy/tests/test_integration.py
  respy/tests/test_likelihood.py
  respy/tests/test_method_of_simulated_moments.py
  respy/tests/test_model_processing.py
  respy/tests/test_randomness.py
  respy/tests/test_regression.py
  respy/tests/test_simulate.py
Labels: enhancement, method-of-simulated-moments

#369 Add new parameters for KW97 models to respy interface.
  codecov.yml
  docs/projects/estimating-keane-and-wolpin-1997-msm.ipynb
  docs/projects/index.rst
  docs/projects/keane-and-wolpin-1997.ipynb
  docs/release_notes.rst
  respy/config.py
  respy/interface.py
  respy/tests/resources/kw_97_basic_respy.csv
  respy/tests/resources/kw_97_basic_respy.yaml
  respy/tests/resources/kw_97_extended_respy.csv
  respy/tests/resources/kw_97_extended_respy.yaml
  respy/tests/test_solve.py
Labels: documentation, enhancement, method-of-simulated-moments

#374 Rename options related to the cache.
  docs/release_notes.rst
  respy/config.py
  respy/pre_processing/model_processing.py
  respy/shared.py
  respy/tests/test_method_of_simulated_moments.py
Labels: ready-for-review

#373 Refactor law of motion.
  docs/release_notes.rst
  respy/_numba.py
  respy/shared.py
  respy/simulate.py
  respy/state_space.py
  respy/tests/test_simulate.py
  tox.ini
Labels: ready-for-review
